[toolchain]

[features]
seeds = false
skip-lint = false

[programs.testnet]
nft_staking = "GGWeSTDbz2WCERf59nTxwSRTFLMg7butvdk9tv4D53sN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "/Users/minh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
